"""Brain-local opaque message references (IDD-2C source_ref).

WHY THIS EXISTS
---------------
`bic_claims.source_ref` used to hold `wa_msg:<wamid>`. A Meta wamid is not
opaque: it base64-embeds the sender's MSISDN. `wamid.HBgMOTE5OTk5MDAwNDQ0FQIAEhgg`
decodes to bytes containing "919999000444". So every claim written from an
inbound message carried the customer's phone number in reversible form, inside
the evidence table, and the privacy tests missed it because they only ever
looked for the number in plaintext.

IDD-2C calls source_ref a "pointer back to the origin record" (§ table at
line 176) — provenance, NOT an external provider identifier. The origin record
is ours: a row in bic_webhook_events. So the pointer should be OUR id.

THE CONTRACT
------------
A reference is `msg:<uuid4>`. The uuid is generated by `secrets`-backed
`uuid4()` — cryptographically random, carrying nothing. It is not derived from
the phone, not derived from the wamid, and not sequential.

WHY reference() VALIDATES INSTEAD OF TRUSTING ITS CALLER
--------------------------------------------------------
`bic/knowledge.py::_source_kind` already learned this lesson: a guarantee that
holds only while every future writer remembers a convention is not a
guarantee. So `reference()` REFUSES anything that is not a bare uuid4 — a
wamid, a phone, a `lead_<phone>` — and returns None rather than formatting it.
Passing the wrong thing therefore produces a claim with no source_ref, which
is visible, instead of a claim with a phone number in it, which is not.

The wamid still exists where the integration genuinely needs it:
bic_webhook_events.wamid remains the PRIMARY KEY and the dedupe mechanism.
This module only stops it reaching the evidence layer.
"""

import re
import uuid
from typing import Optional

SCHEME = "msg"

# A bare uuid — 8-4-4-4-12 hex. Anchored: `wamid.<...>` and `919999000444`
# both fail, which is the entire point.
_UUID_RE = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$")


def new_id() -> str:
    """A fresh Brain-local message id. Random, meaningless, unique."""
    return str(uuid.uuid4())


def is_valid(brain_message_id) -> bool:
    """True only for a bare lowercase uuid."""
    return bool(brain_message_id) and bool(
        _UUID_RE.match(str(brain_message_id)))


def reference(brain_message_id) -> Optional[str]:
    """`msg:<uuid>` for a valid Brain id, otherwise None.

    Returning None is deliberate: source_ref is nullable, and a missing
    provenance pointer is a smaller harm than a reversible identifier stored
    in the evidence table forever.
    """
    if not is_valid(brain_message_id):
        return None
    return f"{SCHEME}:{brain_message_id}"
